apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microshift-lab-root
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/rdiezsj/microshift-lab.git'
    targetRevision: HEAD
    path: argocd-apps/  # La carpeta que contiene las apps hijas
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true