kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-pvc
  namespace: full-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: topolvm-provisioner