kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: keycloak-pvc
  namespace: full-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: topolvm-provisioner